<?php

declare(strict_types=1);

namespace Maradigma\Support;

use WP_Error;
use WP_REST_Request;
use WP_REST_Response;

/**
 * Authorizes public booking writes without requiring a WordPress user account.
 *
 * The booking flow remains available to logged-out visitors. A dedicated
 * nonce prevents blind cross-site submissions, layered fixed-window policies
 * reduce automated abuse, and idempotency protects payment-producing writes
 * from duplicate retries. Identifiers are hashed before transient storage.
 */
final class PublicBookingGuard
{
    public const NONCE_ACTION = 'maradigma_public_booking';
    public const NONCE_HEADER = 'X-Maradigma-Booking-Nonce';
    public const SESSION_HEADER = 'X-Maradigma-Booking-Session';
    public const IDEMPOTENCY_HEADER = 'Idempotency-Key';

    private const IP_LIMIT = 120;
    private const IP_WINDOW_SECONDS = 600;
    private const SESSION_LIMIT = 60;
    private const SESSION_WINDOW_SECONDS = 600;
    private const PAYMENT_CONTEXT_LIMIT = 5;
    private const PAYMENT_CONTEXT_WINDOW_SECONDS = 900;
    private const PAYMENT_IP_LIMIT = 60;
    private const PAYMENT_IP_WINDOW_SECONDS = 3600;
    private const IDEMPOTENCY_TTL = 900;

    /**
     * Registers REST response hooks for standards-compatible throttling.
     */
    public static function registerHooks(): void
    {
        \add_filter('rest_post_dispatch', [self::class, 'addRateLimitHeaders'], 10, 3);
    }

    /**
     * Creates the token sent to the public booking client.
     */
    public static function createNonce(): string
    {
        return \wp_create_nonce(self::NONCE_ACTION);
    }

    /**
     * REST permission callback for endpoints that create or update bookings.
     *
     * @return bool|WP_Error True when the request may continue, otherwise a
     *                       REST-compatible authorization error.
     */
    public static function authorize(WP_REST_Request $request): bool|WP_Error
    {
        $nonce = \sanitize_text_field((string) $request->get_header(self::NONCE_HEADER));

        if ($nonce === '' || !\wp_verify_nonce($nonce, self::NONCE_ACTION)) {
            return new WP_Error(
                'maradigma_booking_invalid_nonce',
                \__('The booking security token is missing or has expired. Reload the page and try again.', 'maradigma'),
                ['status' => 403]
            );
        }

        return self::consumeRateLimit($request);
    }

    /**
     * Consumes one request from the anonymous booking rate limit.
     *
     * @return bool|WP_Error
     */
    private static function consumeRateLimit(WP_REST_Request $request): bool|WP_Error
    {
        $now = (int) \apply_filters('maradigma_booking_rate_now', \time(), $request);
        $policies = self::getRateLimitPolicies($request);
        $buckets = [];

        foreach ($policies as $policy) {
            $key = self::getRateLimitKey($policy['name'], $policy['identity']);
            $bucket = self::getRateLimitBucket($key, $now, $policy['window']);

            if ($bucket['count'] >= $policy['limit']) {
                $retryAfter = \max(1, $bucket['reset_at'] - $now);

                return new WP_Error(
                    'maradigma_booking_rate_limited',
                    \__('Too many booking attempts. Please wait a few minutes and try again.', 'maradigma'),
                    [
                        'status' => 429,
                        'policy' => $policy['name'],
                        'limit' => $policy['limit'],
                        'retry_after' => $retryAfter,
                        'reset_at' => $bucket['reset_at'],
                    ]
                );
            }

            $buckets[] = [$key, $bucket];
        }

        foreach ($buckets as [$key, $bucket]) {
            ++$bucket['count'];
            \set_transient($key, $bucket, \max(1, $bucket['reset_at'] - $now));
        }

        return true;
    }

    /**
     * Adds RFC-compatible retry metadata to throttled REST responses.
     *
     * @param mixed $response REST response generated by WordPress.
     * @param mixed $server REST server instance.
     * @return mixed
     */
    public static function addRateLimitHeaders(mixed $response, mixed $server, WP_REST_Request $request): mixed
    {
        if (!($response instanceof WP_REST_Response) || $response->get_status() !== 429) {
            return $response;
        }

        $route = (string) $request->get_route();
        if ($route === '' || !\str_contains($route, '/maradigma/v1/booking')) {
            return $response;
        }

        $body = $response->get_data();
        $errorData = \is_array($body) && \is_array($body['data'] ?? null) ? $body['data'] : [];
        $retryAfter = \max(1, (int) ($errorData['retry_after'] ?? 60));

        $response->header('Retry-After', (string) $retryAfter);
        if (isset($errorData['limit'])) {
            $response->header('X-RateLimit-Limit', (string) (int) $errorData['limit']);
            $response->header('X-RateLimit-Remaining', '0');
        }
        if (isset($errorData['reset_at'])) {
            $response->header('X-RateLimit-Reset', (string) (int) $errorData['reset_at']);
        }

        return $response;
    }

    /**
     * Claims an idempotency key for a payment-producing booking request.
     *
     * @return array{state:string,key?:string,response?:mixed,status?:int}|WP_Error
     */
    public static function beginIdempotentWrite(WP_REST_Request $request): array|WP_Error
    {
        if (!self::isPaymentRequest($request)) {
            return ['state' => 'disabled'];
        }

        $clientKey = \sanitize_text_field((string) $request->get_header(self::IDEMPOTENCY_HEADER));
        if ($clientKey === '') {
            return ['state' => 'disabled'];
        }

        if (!\preg_match('/^[A-Za-z0-9._:-]{20,128}$/', $clientKey)) {
            return new WP_Error(
                'maradigma_booking_invalid_idempotency_key',
                \__('The booking request identifier is invalid. Reload the page and try again.', 'maradigma'),
                ['status' => 400]
            );
        }

        $key = self::getIdempotencyKey($request, $clientKey);
        $fingerprint = self::getRequestFingerprint($request);
        $existing = \get_transient($key);

        if (\is_array($existing)) {
            if (!\hash_equals((string) ($existing['fingerprint'] ?? ''), $fingerprint)) {
                return new WP_Error(
                    'maradigma_booking_idempotency_conflict',
                    \__('This booking request identifier was already used with different data.', 'maradigma'),
                    ['status' => 409]
                );
            }

            if (($existing['state'] ?? '') === 'complete') {
                return [
                    'state' => 'replay',
                    'key' => $key,
                    'response' => $existing['response'] ?? null,
                    'status' => (int) ($existing['status'] ?? 200),
                ];
            }

            return new WP_Error(
                'maradigma_booking_request_in_progress',
                \__('This booking request is already being processed. Please wait before trying again.', 'maradigma'),
                ['status' => 409, 'retry_after' => 2]
            );
        }

        $claimed = \set_transient(
            $key,
            ['state' => 'processing', 'fingerprint' => $fingerprint],
            self::getIdempotencyTtl($request)
        );
        if (!$claimed) {
            return new WP_Error(
                'maradigma_booking_request_in_progress',
                \__('This booking request is already being processed. Please wait before trying again.', 'maradigma'),
                ['status' => 409, 'retry_after' => 2]
            );
        }

        return ['state' => 'claimed', 'key' => $key];
    }

    /**
     * Stores the successful response associated with an idempotency claim.
     *
     * @param array{state:string,key?:string} $claim
     */
    public static function completeIdempotentWrite(
        array $claim,
        WP_REST_Request $request,
        mixed $response,
        int $status = 200
    ): void {
        if (($claim['state'] ?? '') !== 'claimed' || empty($claim['key'])) {
            return;
        }

        \set_transient(
            (string) $claim['key'],
            [
                'state' => 'complete',
                'fingerprint' => self::getRequestFingerprint($request),
                'response' => $response,
                'status' => $status,
            ],
            self::getIdempotencyTtl($request)
        );
    }

    /**
     * Releases a failed idempotency claim so it can be retried.
     *
     * @param array{state:string,key?:string} $claim
     */
    public static function abortIdempotentWrite(array $claim): void
    {
        if (($claim['state'] ?? '') === 'claimed' && !empty($claim['key'])) {
            \delete_transient((string) $claim['key']);
        }
    }

    /**
     * Determines whether an external API result represents success.
     */
    public static function isSuccessfulResult(mixed $result): bool
    {
        if (!\is_array($result)) {
            return false;
        }

        return isset($result['success']) ? (bool) $result['success'] : !isset($result['error']);
    }

    /**
     * Builds the policies applicable to the current request.
     *
     * @return list<array{name:string,identity:string,limit:int,window:int}>
     */
    private static function getRateLimitPolicies(WP_REST_Request $request): array
    {
        $ipIdentity = self::getClientIdentity();
        $policies = [[
            'name' => 'ip',
            'identity' => $ipIdentity,
            'limit' => (int) \apply_filters('maradigma_booking_rate_limit', self::IP_LIMIT, $request),
            'window' => (int) \apply_filters(
                'maradigma_booking_rate_window',
                self::IP_WINDOW_SECONDS,
                $request
            ),
        ]];

        $session = self::getSessionToken($request);
        if ($session !== '') {
            $policies[] = [
                'name' => 'session',
                'identity' => 'session|' . $session,
                'limit' => self::SESSION_LIMIT,
                'window' => self::SESSION_WINDOW_SECONDS,
            ];
        }

        if (self::isPaymentRequest($request)) {
            $params = $request->get_json_params() ?? [];
            $cart = \sanitize_text_field((string) ($params['uuid_shop_cart'] ?? ''));
            $context = $cart !== ''
                ? 'cart|' . $cart
                : ($session !== '' ? 'session|' . $session : $ipIdentity);

            $policies[] = [
                'name' => 'payment_context',
                'identity' => $context,
                'limit' => self::PAYMENT_CONTEXT_LIMIT,
                'window' => self::PAYMENT_CONTEXT_WINDOW_SECONDS,
            ];
            $policies[] = [
                'name' => 'payment_ip',
                'identity' => $ipIdentity,
                'limit' => self::PAYMENT_IP_LIMIT,
                'window' => self::PAYMENT_IP_WINDOW_SECONDS,
            ];
        }

        /**
         * Filters public booking rate-limit policies.
         *
         * Each entry must contain name, identity, limit and window keys.
         *
         * @param array<int,array{name:string,identity:string,limit:int,window:int}> $policies
         * @param WP_REST_Request $request
         */
        $filtered = \apply_filters('maradigma_booking_rate_policies', $policies, $request);
        if (!\is_array($filtered)) {
            $filtered = $policies;
        }

        $normalized = [];
        foreach ($filtered as $policy) {
            if (!\is_array($policy) || empty($policy['name']) || empty($policy['identity'])) {
                continue;
            }

            $normalized[] = [
                'name' => \sanitize_key((string) $policy['name']),
                'identity' => (string) $policy['identity'],
                'limit' => \max(1, (int) ($policy['limit'] ?? 1)),
                'window' => \max(60, (int) ($policy['window'] ?? 60)),
            ];
        }

        return $normalized;
    }

    /**
     * Reads a fixed-window counter, resetting it only after its deadline.
     *
     * @return array{count:int,reset_at:int}
     */
    private static function getRateLimitBucket(string $key, int $now, int $window): array
    {
        $stored = \get_transient($key);
        if (!\is_array($stored) || (int) ($stored['reset_at'] ?? 0) <= $now) {
            return ['count' => 0, 'reset_at' => $now + $window];
        }

        return [
            'count' => \max(0, (int) ($stored['count'] ?? 0)),
            'reset_at' => (int) $stored['reset_at'],
        ];
    }

    /**
     * Builds a privacy-preserving transient key.
     */
    private static function getRateLimitKey(string $policy, string $identity): string
    {
        $hash = \hash_hmac('sha256', $identity, \wp_salt('nonce'));

        return 'maradigma_booking_rate_' . $policy . '_' . \substr($hash, 0, 28);
    }

    /**
     * Returns a validated anonymous browser-session token.
     */
    private static function getSessionToken(WP_REST_Request $request): string
    {
        $token = \sanitize_text_field((string) $request->get_header(self::SESSION_HEADER));

        return \preg_match('/^[A-Za-z0-9_-]{20,128}$/', $token) ? $token : '';
    }

    /**
     * Determines whether the request can create a booking or payment.
     */
    private static function isPaymentRequest(WP_REST_Request $request): bool
    {
        $route = (string) $request->get_route();
        if ($route !== '' && \str_ends_with($route, '/booking')) {
            return true;
        }

        $params = $request->get_json_params() ?? [];

        return (int) ($params['step'] ?? 0) >= 3;
    }

    /**
     * Returns the current client identity without persisting the raw address.
     */
    private static function getClientIdentity(): string
    {
        $remoteAddress = isset($_SERVER['REMOTE_ADDR'])
            ? \sanitize_text_field((string) \wp_unslash($_SERVER['REMOTE_ADDR']))
            : '';
        $userAgent = isset($_SERVER['HTTP_USER_AGENT'])
            ? \sanitize_text_field((string) \wp_unslash($_SERVER['HTTP_USER_AGENT']))
            : '';

        if ($remoteAddress !== '' && \filter_var($remoteAddress, FILTER_VALIDATE_IP) === false) {
            $remoteAddress = '';
        }

        return $remoteAddress !== ''
            ? 'ip|' . $remoteAddress
            : 'ua|' . $userAgent;
    }

    private static function getIdempotencyKey(WP_REST_Request $request, string $clientKey): string
    {
        $value = (string) $request->get_route() . '|' . $clientKey;
        $hash = \hash_hmac('sha256', $value, \wp_salt('nonce'));

        return 'maradigma_booking_idem_' . \substr($hash, 0, 32);
    }

    private static function getRequestFingerprint(WP_REST_Request $request): string
    {
        $params = $request->get_json_params() ?? [];
        self::sortRecursively($params);
        $json = \wp_json_encode($params);

        return \hash('sha256', \is_string($json) ? $json : '');
    }

    /** @param array<mixed> $value */
    private static function sortRecursively(array &$value): void
    {
        foreach ($value as &$item) {
            if (\is_array($item)) {
                self::sortRecursively($item);
            }
        }
        unset($item);

        if (!\array_is_list($value)) {
            \ksort($value);
        }
    }

    private static function getIdempotencyTtl(WP_REST_Request $request): int
    {
        return \max(
            60,
            (int) \apply_filters('maradigma_booking_idempotency_ttl', self::IDEMPOTENCY_TTL, $request)
        );
    }
}
