<?php
declare(strict_types=1);

namespace Maradigma;

if (!defined('ABSPATH')) {
    exit;
}

use Maradigma\Support\RuntimeContext;

/**
 * Yoast SEO integration for maradigma_boat CPT.
 *
 * Goals:
 * - On sync: write Yoast meta title/desc computed from templates (plugin settings),
 *   BUT never override if user already set Yoast meta manually.
 * - On frontend: provide fallback via Yoast filters ONLY when current value is not meaningful
 *   AND user has not set Yoast meta manually.
 *
 * Notes:
 * - Uses boat payload stored in: _maradigma_boat_payload (JSON)
 * - Uses plugin templates from SettingsPage::getSettings():
 *   - seo_title_template
 *   - seo_meta_description_template
 *
 * Multi-language templates:
 * - Supports simple format: "es:...,en:...,de:...,ca:..."
 * - Uses SettingsPage::pickLocalizedValue() to select the right string for the current language.
 */
final class SeoIntegration
{
    /**
     * Yoast post meta keys.
     */
    private const YOAST_TITLE_META = '_yoast_wpseo_title';
    private const YOAST_DESC_META  = '_yoast_wpseo_metadesc';

    /**
     * Your plugin stored boat payload meta.
     */
    private const META_BOAT_PAYLOAD = '_maradigma_boat_payload';

    /**
     * Track what Maradigma generated last time (per-post).
     * These hashes allow us to safely overwrite only our own values in later syncs.
     */
    private const META_MD_YOAST_TITLE_HASH = '_maradigma_yoast_title_hash';
    private const META_MD_YOAST_DESC_HASH  = '_maradigma_yoast_desc_hash';

    /**
     * Registers the component's WordPress hooks.
     */
    public static function init(): void
    {
        // Frontend filters (fallback only)
        \add_filter('wpseo_title', [__CLASS__, 'filterYoastTitle'], 20, 1);
        \add_filter('wpseo_metadesc', [__CLASS__, 'filterYoastMetadesc'], 20, 1);

        // OG tags
        \add_filter('wpseo_opengraph_title', [__CLASS__, 'filterYoastOgTitle'], 20, 1);
        \add_filter('wpseo_opengraph_desc', [__CLASS__, 'filterYoastOgDesc'], 20, 1);
    }

    /**
     * Apply Yoast meta to a boat post during sync (create/update).
     *
     * Modes:
     * - skip: do nothing
     * - missing: only fill if empty OR if it was previously generated by Maradigma (hash matches)
     * - fix_multilang: if current Yoast meta looks like "es:...,en:..." -> recompute and write
     *                  OR if it was previously generated by Maradigma (hash matches)
     * - force: overwrite always
     *
     * IMPORTANT:
     * - This method must NOT use "current runtime language" from the admin request.
     * - The caller (sync) MUST pass the language explicitly via $options['lang'].
     *
     * @param int $postId
     * @param array<string,mixed> $boatData
     * @param array{mode?:'skip'|'missing'|'fix_multilang'|'force', lang?:string} $options
     */
    public static function applyYoastMetaToPost(int $postId, array $boatData, array $options = []): void
    {
        if ($postId <= 0 || !self::isBoatPost($postId)) {
            return;
        }

        $mode = isset($options['mode']) ? (string) $options['mode'] : 'missing';
        if ($mode === 'skip') {
            return;
        }

        $settings = SettingsPage::getSettings();

        // ✅ Use explicit lang if provided (sync passes it)
        $lang = isset($options['lang']) ? (string) $options['lang'] : '';
        $lang = \strtolower(\trim($lang));

        // Fallbacks only if caller didn't provide a lang
        if ($lang === '') {
            $lang = RuntimeContext::detectCurrentLanguage();
        }
        if (\trim($lang) === '') {
            $lang = RuntimeContext::getPluginDefaultLanguage();
        }
        $lang = \strtolower(\trim($lang));
        if ($lang === '') {
            $lang = 'en';
        }

        $fallback = (string) ($settings['default_language'] ?? 'en');
        $fallback = \strtolower(\trim($fallback));
        if ($fallback === '') {
            $fallback = 'en';
        }

        $titleTplRaw = (string) ($settings['seo_title_template'] ?? '');
        $descTplRaw  = (string) ($settings['seo_meta_description_template'] ?? '');

        $titleTpl = SettingsPage::pickLocalizedValue($titleTplRaw, $lang, $fallback);
        $descTpl  = SettingsPage::pickLocalizedValue($descTplRaw,  $lang, $fallback);

        $tokens = self::buildSeoTokenValues($boatData, $lang);

        $computedTitle = self::renderTemplateToPlainText($titleTpl, $tokens);
        $computedDesc  = self::renderTemplateToPlainText($descTpl, $tokens);

        if ($computedTitle === '' && $computedDesc === '') {
            return;
        }

        $currentTitleMeta = (string) \get_post_meta($postId, self::YOAST_TITLE_META, true);
        $currentDescMeta  = (string) \get_post_meta($postId, self::YOAST_DESC_META, true);

        $looksMultilang = static function (string $v): bool {
            $v = \trim($v);
            if ($v === '') return false;
            return (bool) \preg_match('/\b(es|en|fr|de|it|nl|ca)\s*:/i', $v);
        };

        // ✅ Determine if current meta was previously generated by Maradigma
        $storedTitleHash = (string) \get_post_meta($postId, self::META_MD_YOAST_TITLE_HASH, true);
        $storedDescHash  = (string) \get_post_meta($postId, self::META_MD_YOAST_DESC_HASH, true);

        $currentTitleHash = \md5(\trim($currentTitleMeta));
        $currentDescHash  = \md5(\trim($currentDescMeta));

        $isMaradigmaTitle = ($storedTitleHash !== '' && \hash_equals($storedTitleHash, $currentTitleHash));
        $isMaradigmaDesc  = ($storedDescHash !== '' && \hash_equals($storedDescHash, $currentDescHash));

        // ✅ In fix_multilang, consider "es:...,en:..." NOT manual
        if ($mode === 'fix_multilang' && $looksMultilang($currentTitleMeta)) {
            $isMaradigmaTitle = true;
        }
        if ($mode === 'fix_multilang' && $looksMultilang($currentDescMeta)) {
            $isMaradigmaDesc = true;
        }

        $canWriteTitle = false;
        $canWriteDesc  = false;

        if ($mode === 'force') {
            $canWriteTitle = ($computedTitle !== '');
            $canWriteDesc  = ($computedDesc !== '');
        } elseif ($mode === 'missing') {
            // Write only if empty OR previously generated by Maradigma
            $canWriteTitle = ($computedTitle !== '' && (\trim($currentTitleMeta) === '' || $isMaradigmaTitle));
            $canWriteDesc  = ($computedDesc !== ''  && (\trim($currentDescMeta) === ''  || $isMaradigmaDesc));
        } elseif ($mode === 'fix_multilang') {
            // Fix if looksMultilang OR empty OR previously generated by Maradigma
            $canWriteTitle = ($computedTitle !== '' && (
                \trim($currentTitleMeta) === '' || $looksMultilang($currentTitleMeta) || $isMaradigmaTitle
            ));
            $canWriteDesc = ($computedDesc !== '' && (
                \trim($currentDescMeta) === '' || $looksMultilang($currentDescMeta) || $isMaradigmaDesc
            ));
        } else {
            // fallback safety
            $canWriteTitle = ($computedTitle !== '' && \trim($currentTitleMeta) === '');
            $canWriteDesc  = ($computedDesc !== ''  && \trim($currentDescMeta) === '');
        }

        if ($canWriteTitle) {
            \update_post_meta($postId, self::YOAST_TITLE_META, $computedTitle);
            \update_post_meta($postId, self::META_MD_YOAST_TITLE_HASH, \md5(\trim($computedTitle)));
        }

        if ($canWriteDesc) {
            \update_post_meta($postId, self::YOAST_DESC_META, $computedDesc);
            \update_post_meta($postId, self::META_MD_YOAST_DESC_HASH, \md5(\trim($computedDesc)));
        }
    }

    // ─────────────────────────────────────────────
    // Yoast filters (frontend fallback)
    // ─────────────────────────────────────────────

    /**
     * Filters the Yoast SEO document title for a boat post.
     */
    public static function filterYoastTitle(string $current): string
    {
        $postId = self::getCurrentPostId();
        if ($postId <= 0 || !self::isBoatPost($postId)) {
            return $current;
        }

        // If user set Yoast title manually, do not touch
        if (self::hasManualYoastMeta($postId, self::YOAST_TITLE_META)) {
            return $current;
        }

        // If Yoast already has a meaningful title (resolved), do not override
        if (self::isMeaningfulYoastValue($current)) {
            return $current;
        }

        $boatData = self::getBoatPayloadFromPost($postId);
        if ($boatData === null) {
            return $current;
        }

        $settings = SettingsPage::getSettings();

        // ✅ Frontend must use real language (Polylang/WPML) - RuntimeContext should do that.
        $lang = RuntimeContext::detectCurrentLanguage();
        if (\trim($lang) === '') {
            $lang = RuntimeContext::getPluginDefaultLanguage();
        }
        $lang = \strtolower(\trim($lang));
        if ($lang === '') {
            $lang = 'en';
        }

        $fallback = (string) ($settings['default_language'] ?? 'en');
        $fallback = \strtolower(\trim($fallback));
        if ($fallback === '') {
            $fallback = 'en';
        }

        $tplRaw = (string) ($settings['seo_title_template'] ?? '');
        $tpl = SettingsPage::pickLocalizedValue($tplRaw, $lang, $fallback);

        if (\trim($tpl) === '') {
            return $current;
        }

        $tokens = self::buildSeoTokenValues($boatData, $lang);
        $computed = self::renderTemplateToPlainText($tpl, $tokens);

        return $computed !== '' ? $computed : $current;
    }

    /**
     * Filters the Yoast SEO meta description for a boat post.
     */
    public static function filterYoastMetadesc(string $current): string
    {
        $postId = self::getCurrentPostId();
        if ($postId <= 0 || !self::isBoatPost($postId)) {
            return $current;
        }

        // If user set Yoast metadesc manually, do not touch
        if (self::hasManualYoastMeta($postId, self::YOAST_DESC_META)) {
            return $current;
        }

        // If Yoast already has a meaningful description, do not override
        if (self::isMeaningfulYoastValue($current)) {
            return $current;
        }

        $boatData = self::getBoatPayloadFromPost($postId);
        if ($boatData === null) {
            return $current;
        }

        $settings = SettingsPage::getSettings();

        // ✅ Frontend must use real language (Polylang/WPML)
        $lang = RuntimeContext::detectCurrentLanguage();
        if (\trim($lang) === '') {
            $lang = RuntimeContext::getPluginDefaultLanguage();
        }
        $lang = \strtolower(\trim($lang));
        if ($lang === '') {
            $lang = 'en';
        }

        $fallback = (string) ($settings['default_language'] ?? 'en');
        $fallback = \strtolower(\trim($fallback));
        if ($fallback === '') {
            $fallback = 'en';
        }

        $tplRaw = (string) ($settings['seo_meta_description_template'] ?? '');
        $tpl = SettingsPage::pickLocalizedValue($tplRaw, $lang, $fallback);

        if (\trim($tpl) === '') {
            return $current;
        }

        $tokens = self::buildSeoTokenValues($boatData, $lang);
        $computed = self::renderTemplateToPlainText($tpl, $tokens);

        return $computed !== '' ? $computed : $current;
    }

    /**
     * Filters the Yoast Open Graph title for a boat post.
     */
    public static function filterYoastOgTitle(string $current): string
    {
        return self::filterYoastTitle($current);
    }

    /**
     * Filters the Yoast Open Graph description for a boat post.
     */
    public static function filterYoastOgDesc(string $current): string
    {
        return self::filterYoastMetadesc($current);
    }

    // ─────────────────────────────────────────────
    // Helpers
    // ─────────────────────────────────────────────

    /**
     * Returns current post ID.
     */
    private static function getCurrentPostId(): int
    {
        $postId = 0;

        if (\function_exists('get_queried_object_id')) {
            $postId = (int) \get_queried_object_id();
        }

        if ($postId <= 0 && isset($GLOBALS['post']) && $GLOBALS['post'] instanceof \WP_Post) {
            $postId = (int) $GLOBALS['post']->ID;
        }

        return $postId;
    }

    /**
     * Determines whether boat post.
     */
    private static function isBoatPost(int $postId): bool
    {
        $pt = (string) \get_post_type($postId);
        return $pt === BoatPostType::POST_TYPE;
    }

    /**
     * Consider "manual Yoast meta" if post meta exists and is non-empty after trim.
     */
    private static function hasManualYoastMeta(int $postId, string $metaKey): bool
    {
        $v = (string) \get_post_meta($postId, $metaKey, true);
        $v = \trim(\wp_strip_all_tags(\html_entity_decode($v, ENT_QUOTES, 'UTF-8')));
        return $v !== '';
    }

    /**
     * "Meaningful" Yoast value:
     * - not empty after stripping tags
     * - does not contain unreplaced Yoast variables like %%title%%
     * - not just separators / noise
     */
    private static function isMeaningfulYoastValue(string $value): bool
    {
        $v = \trim(\wp_strip_all_tags(\html_entity_decode($value, ENT_QUOTES, 'UTF-8')));

        if ($v === '') {
            return false;
        }

        // If Yoast variables appear unreplaced, it's not meaningful
        if (\strpos($v, '%%') !== false) {
            return false;
        }

        // If it's extremely short, treat as not meaningful
        if (\mb_strlen($v) < 3) {
            return false;
        }

        // Avoid titles/descs that are only punctuation/separators
        $onlyNoise = \preg_replace('/[[:alnum:]]+/u', '', $v);
        $onlyNoise = \trim((string) $onlyNoise);
        if ($onlyNoise !== '' && \mb_strlen($v) === \mb_strlen($onlyNoise)) {
            return false;
        }

        return true;
    }

    /**
     * Read boat payload from post meta.
     *
     * @return array<string,mixed>|null
     */
    private static function getBoatPayloadFromPost(int $postId): ?array
    {
        $json = (string) \get_post_meta($postId, self::META_BOAT_PAYLOAD, true);
        $json = \trim($json);

        if ($json === '') {
            return null;
        }

        $decoded = \json_decode($json, true);
        return \is_array($decoded) ? $decoded : null;
    }

    /**
     * Build a token map for SEO templates.
     *
     * We intentionally build "plain" tokens (no HTML) and then sanitize final result.
     *
     * @param array<string,mixed> $boat
     * @return array<string,string>
     */
    private static function buildSeoTokenValues(array $boat, string $lang): array
    {
        $out = [];

        $id   = (string) ($boat['id'] ?? $boat['id_gi'] ?? $boat['id_group_item'] ?? '');
        $slug = (string) ($boat['slug'] ?? $boat['service_slug'] ?? '');

        $serviceName = (string) ($boat['service_name'] ?? $boat['name'] ?? $boat['title'] ?? '');
        $serviceName = \trim($serviceName);

        $port = (string) ($boat['boat_base_port_name'] ?? $boat['port'] ?? '');
        $port = \trim($port);

        $pax = (string) ($boat['boat_capacity'] ?? $boat['pax'] ?? '');
        $pax = \trim($pax);

        $priceFrom = (string) ($boat['price_from'] ?? $boat['base_price'] ?? '');
        $priceFrom = \trim($priceFrom);

        $destination = BoatUrlResolver::getDestinationName($boat);
        $destinationSlug = BoatUrlResolver::getDestinationSlug($boat);

        // URL
        $url = BoatUrlResolver::buildBoatUrl($boat, $lang, $slug !== '' ? $slug : $id);

        // Fill all tokens declared in BoatCardEngine, default empty
        foreach (BoatCardEngine::listTokens() as $token) {
            $out[$token] = '';
        }

        // Common SEO-used tokens (plus whatever exists in payload)
        $out['id'] = $id;
        $out['slug'] = $slug;
        $out['url'] = $url;

        $out['service_name'] = $serviceName;
        $out['name'] = $serviceName !== '' ? $serviceName : (string) ($boat['boat_alias'] ?? '');

        $out['port'] = $port;
        $out['destination'] = $destination;
        $out['destination_slug'] = $destinationSlug;
        $out['pax'] = $pax;
        $out['price_from'] = $priceFrom;

        // Copy raw fields if present (so templates can use them)
        foreach ($out as $k => $v) {
            if ($v !== '') {
                continue;
            }
            if (\array_key_exists($k, $boat) && !\is_array($boat[$k]) && !\is_object($boat[$k])) {
                $out[$k] = (string) $boat[$k];
            }
        }

        // Ensure scalar strings, no HTML
        foreach ($out as $k => $v) {
            $out[$k] = \trim(\wp_strip_all_tags((string) $v));
        }

        return $out;
    }

    /**
     * Render {{token}} template to a plain-text string.
     *
     * @param string $template
     * @param array<string,string> $tokens
     */
    private static function renderTemplateToPlainText(string $template, array $tokens): string
    {
        $tpl = \trim($template);
        if ($tpl === '') {
            return '';
        }

        foreach ($tokens as $token => $value) {
            $needle = '{{' . $token . '}}';
            if (\strpos($tpl, $needle) === false) {
                continue;
            }
            $tpl = \str_replace($needle, $value, $tpl);
        }

        // Remove unresolved {{...}} leftovers
        $tpl = \preg_replace('/\{\{[a-z0-9\-_]+\}\}/i', '', $tpl) ?: $tpl;

        // Normalize whitespace
        $tpl = \trim(\preg_replace('/\s+/u', ' ', $tpl) ?: $tpl);

        // Final plain text
        $tpl = \wp_strip_all_tags($tpl);
        $tpl = \trim($tpl);

        return $tpl;
    }
}
